# Every `nix run .#<app>` in one place. Three jobs, nothing else:
#   install   net-setup (host tap + NAT), host-install (the proxy unit)
#   run       microvm (boot the guest)
#   propagate users, seed, clients, provision (demo data onto guest + clients)
#
# Shell bodies live in ./scripts/*.sh; this file is what turns them into
# packages: it renders ./services.nix into the shell data every script gets,
# declares each script's runtime tools (so no script guesses at $PATH), and
# generates the host proxy config from that same data — the guest IP and the
# service prefixes are never written down twice.
{
  pkgs,
  lib,
}: let
  demo = import ./services.nix {inherit lib;};
  inherit (demo) guest services infra;

  # --- shell view of ./services.nix -------------------------------------------
  # Rendered as shell data so scripts can target one service, or loop over all
  # of them, without hardcoding domains/manage-commands.
  servicesSh = let
    # Read only via lib.sh's eval-based service_*() lookups, so shellcheck
    # can't see the use — silence its SC2034 per line rather than file-wide
    # (keeps the check meaningful elsewhere). Force single quotes (rather than
    # lib.escapeShellArg's leave-bare-when-safe behavior): unquoted
    # `tap-selfhostix`-shaped values trip shellcheck's SC2100 heuristic.
    var = name: value: ''
      # shellcheck disable=SC2034
      ${name}='${value}'
    '';
    field = name: attr: var "${name}_${lib.toUpper attr}" services.${name}.${attr};
    fields = lib.concatMap (name: map (field name) ["domain" "manage"]) (lib.attrNames services);
  in ''
    # Generated by nix/apps.nix from nix/services.nix — do not hand-edit.
    DEMO_SERVICES=${lib.escapeShellArg (lib.concatStringsSep " " (lib.attrNames services))}
    ${var "DEMO_DOMAINS" (lib.concatStringsSep " " demo.domains)}
    ${var "GUEST_HOST" guest.hostName}
    ${var "GUEST_TAP" guest.tap}
    ${var "GUEST_GATEWAY" guest.gateway}
    GUEST_IP='${guest.ip}'
    ${lib.concatStringsSep "\n" fields}
  '';

  # ./scripts/lib.sh has no shebang/options of its own — it's concatenated
  # ahead of every app script (after the service data above), which each start
  # with their own `set -euo pipefail` (see lib.sh's header comment).
  libSh = builtins.readFile ./scripts/lib.sh;
  scriptText = name: servicesSh + "\n" + libSh + "\n" + builtins.readFile (./scripts + "/${name}.sh");

  # --- host reverse proxy ------------------------------------------------------
  # One TLS vhost per name, each forwarding plain HTTP over the tap link.
  # Name-based, not path-based: Docs and Drive are both SPAs that call
  # /api/v1.0/... at their origin root, so a stripped prefix would send
  # Drive's API calls to Docs.
  #
  # The certificate and its CA are generated once by host-install (they cannot
  # live in the flake — they are per install and hold a private key); the paths
  # below are where it puts them.
  certDir = "/etc/selfhostix-demo/certs";

  # Caddy sets X-Forwarded-For/Host/Proto itself, so the header block an nginx
  # proxy needs is absent on purpose. Proto arrives as https, which is what
  # tells Django the request was secure (DJANGO_SECURE_PROXY_SSL_HEADER).
  site = domain: upstream:
    lib.concatMapStrings (line:
      if line == ""
      then "\n"
      else "${line}\n") [
      "https://${domain} {"
      "\tbind 0.0.0.0"
      "\ttls ${certDir}/site.crt ${certDir}/site.key"
      "\treverse_proxy ${upstream}"
      "}"
      ""
    ];
  appSites = lib.mapAttrsToList (_: s: site s.domain "${guest.ip}:80") services;
  infraSites = lib.mapAttrsToList (_: s: site s.domain "${guest.ip}:${toString s.port}") infra;
  caddyfile = pkgs.writeText "selfhostix-Caddyfile" ''
    # Generated by nix/apps.nix from nix/services.nix — do not hand-edit.
    # Install with: sudo nix run .#host-install
    #
    # auto_https off: the certificate is the demo CA's, issued by host-install,
    # so Caddy must neither reach out to an ACME server nor manage renewals.
    # The redirect it would normally add is written out below instead.
    {
    	auto_https off
    }

    ${lib.concatStrings (appSites ++ infraSites)}http://${lib.concatStringsSep ", http://" demo.domains} {
    	redir https://{host}{uri} permanent
    }
  '';

  # Host systemd unit for the proxy, rendered from nixpkgs' own Caddy build
  # (no `nix run` at runtime, no hardcoded checkout path).
  caddyUnit = pkgs.writeText "selfhostix-caddy.service" ''
    [Unit]
    Description=Host reverse proxy (Caddy, multi-service entrypoint)
    After=network-online.target
    Wants=network-online.target

    [Service]
    Type=simple
    WorkingDirectory=/etc/selfhostix-demo
    ExecStart=${lib.getExe pkgs.caddy} run --config /etc/selfhostix-demo/Caddyfile --adapter caddyfile
    Restart=on-failure
    RestartSec=5
    AmbientCapabilities=CAP_NET_BIND_SERVICE

    [Install]
    WantedBy=multi-user.target
  '';

  # host-install is the only script carrying generated files into /etc; it
  # also issues the certificate those files reference, hence @CERTDIR@/@SANS@.
  substitutions = {
    "@CADDYFILE@" = "${caddyfile}";
    "@SERVICE@" = "${caddyUnit}";
    "@CERTDIR@" = certDir;
    "@SANS@" = lib.concatStringsSep "," (map (d: "DNS:${d}") demo.domains);
  };
  substituted = name:
    builtins.replaceStrings
    (lib.attrNames substitutions)
    (lib.attrValues substitutions)
    (scriptText name);

  app = name: {
    runtimeInputs ? [],
    text ? scriptText name,
  }:
    pkgs.writeShellApplication {inherit name runtimeInputs text;};

  # Tools the user-propagation flow needs on every hop (host -> guest -> clients).
  propagationInputs = with pkgs; [
    openssh
    sshpass
    curl
    python3
    coreutils
    gnused
    gawk
  ];

  scripts = {
    detect-origin = app "detect-origin" {runtimeInputs = with pkgs; [iproute2 gawk];};
    net-setup = app "net-setup" {runtimeInputs = with pkgs; [iproute2 nftables iptables];};
    host-install = app "host-install" {
      runtimeInputs = with pkgs; [coreutils systemd openssl];
      text = substituted "host-install";
    };
    microvm = app "microvm" {
      runtimeInputs = with pkgs; [nix iproute2 coreutils];
    };
    users = app "users" {runtimeInputs = propagationInputs;};
    seed = app "seed" {runtimeInputs = propagationInputs;};
    provision = app "provision" {
      runtimeInputs = propagationInputs ++ [scripts.detect-origin];
    };
    clients = app "clients" {
      runtimeInputs = propagationInputs ++ [pkgs.nix scripts.provision];
    };
  };
in
  scripts
