# Every `nix run .#<app>` in one place. Three jobs, nothing else:
#   install   net-setup (host tap + NAT), host-install (the proxy unit)
#   run       microvm (boot the guest)
#   propagate users, seed, clients, provision (demo data onto guest + clients)
#
# Shell bodies live in ./scripts/*.sh; this file is what turns them into
# packages: it renders ./services.nix into the shell data every script gets,
# declares each script's runtime tools (so no script guesses at $PATH), and
# generates the host proxy config from that same data — the guest IP and the
# service prefixes are never written down twice.
{
  pkgs,
  lib,
}: let
  demo = import ./services.nix {inherit lib;};
  inherit (demo) guest services;

  # --- shell view of ./services.nix -------------------------------------------
  # Rendered as shell data so scripts can target one service, or loop over all
  # of them, without hardcoding domains/manage-commands.
  servicesSh = let
    # Read only via lib.sh's eval-based service_*() lookups, so shellcheck
    # can't see the use — silence its SC2034 per line rather than file-wide
    # (keeps the check meaningful elsewhere). Force single quotes (rather than
    # lib.escapeShellArg's leave-bare-when-safe behavior): unquoted
    # `tap-selfhostix`-shaped values trip shellcheck's SC2100 heuristic.
    var = name: value: ''
      # shellcheck disable=SC2034
      ${name}='${value}'
    '';
    field = name: attr: var "${name}_${lib.toUpper attr}" services.${name}.${attr};
    fields = lib.concatMap (name: map (field name) ["domain" "manage"]) (lib.attrNames services);
  in ''
    # Generated by nix/apps.nix from nix/services.nix — do not hand-edit.
    DEMO_SERVICES=${lib.escapeShellArg (lib.concatStringsSep " " (lib.attrNames services))}
    ${var "GUEST_HOST" guest.hostName}
    ${var "GUEST_TAP" guest.tap}
    ${var "GUEST_GATEWAY" guest.gateway}
    GUEST_IP='${guest.ip}'
    ${lib.concatStringsSep "\n" fields}
  '';

  # ./scripts/lib.sh has no shebang/options of its own — it's concatenated
  # ahead of every app script (after the service data above), which each start
  # with their own `set -euo pipefail` (see lib.sh's header comment).
  libSh = builtins.readFile ./scripts/lib.sh;
  scriptText = name: servicesSh + "\n" + libSh + "\n" + builtins.readFile (./scripts + "/${name}.sh");

  # --- host reverse proxy ------------------------------------------------------
  # Single LAN entrypoint: browsers open the host IP, no per-service DNS and no
  # /etc/hosts edits. Prefixed services first, the catch-all last (which keeps
  # Docs' /collaboration websockets working).
  #
  # handle_path strips the prefix before proxying, so the backend sees /... as
  # if served from root, and `header_up Host` names the guest vhost the request
  # belongs to — one guest IP serves every service, so Host is what tells its
  # nginx which one is meant. The catch-all service is the guest's default
  # server and keeps the original Host, so it needs no rewrite.
  #
  # No X-Forwarded-* here on purpose: Caddy sets X-Forwarded-For/Host/Proto
  # itself, and its X-Forwarded-Host keeps the browser's original host even
  # after the rewrite above (verified against a live upstream). An nginx proxy
  # would need the headers spelled out; Caddy does not.
  #
  # Indentation is written out explicitly: Nix strips the common indent of a
  # literal block but never re-indents an interpolated one, so a nested
  # template would land flush against the margin in the generated file.
  proxyRoute = name: s:
    lib.concatMapStrings (line:
      if line == ""
      then "\n"
      else "\t${line}\n") [
      "# --- ${name} (${s.domain}) ---"
      "handle_path ${s.prefix}/* {"
      "\treverse_proxy ${guest.ip}:80 {"
      "\t\theader_up Host ${s.domain}"
      "\t}"
      "}"
    ];
  prefixed = lib.filterAttrs (_: s: s.prefix != null) services;
  catchAll = lib.head (lib.attrValues (lib.filterAttrs (_: s: s.prefix == null) services));
  caddyfile = pkgs.writeText "selfhostix-Caddyfile" ''
    # Generated by nix/apps.nix from nix/services.nix — do not hand-edit.
    # Install with: sudo nix run .#host-install
    #
    # NOTE: bare-IP browser access needs the origin trusted by Django as well;
    # booting the guest via `nix run .#microvm` auto-exports
    # SELFHOSTIX_PUBLIC_ORIGIN=http://<host-LAN-IP> for this (see
    # nix/scripts/detect-origin.sh).
    {
    	auto_https off
    }

    :80 {
    	bind 0.0.0.0

    ${lib.concatStrings (lib.mapAttrsToList proxyRoute prefixed)}
    	# --- ${catchAll.domain}: everything else ---
    	handle {
    		reverse_proxy ${guest.ip}:80
    	}
    }
  '';

  # Host systemd unit for the proxy, rendered from nixpkgs' own Caddy build
  # (no `nix run` at runtime, no hardcoded checkout path).
  caddyUnit = pkgs.writeText "selfhostix-caddy.service" ''
    [Unit]
    Description=Host reverse proxy (Caddy, multi-service entrypoint)
    After=network-online.target
    Wants=network-online.target

    [Service]
    Type=simple
    WorkingDirectory=/etc/selfhostix-demo
    ExecStart=${lib.getExe pkgs.caddy} run --config /etc/selfhostix-demo/Caddyfile --adapter caddyfile
    Restart=on-failure
    RestartSec=5
    AmbientCapabilities=CAP_NET_BIND_SERVICE

    [Install]
    WantedBy=multi-user.target
  '';

  # host-install is the only script carrying generated files into /etc.
  substitutions = {
    "@CADDYFILE@" = "${caddyfile}";
    "@SERVICE@" = "${caddyUnit}";
  };
  substituted = name:
    builtins.replaceStrings
    (lib.attrNames substitutions)
    (lib.attrValues substitutions)
    (scriptText name);

  app = name: {
    runtimeInputs ? [],
    text ? scriptText name,
  }:
    pkgs.writeShellApplication {inherit name runtimeInputs text;};

  # Tools the user-propagation flow needs on every hop (host -> guest -> clients).
  propagationInputs = with pkgs; [
    openssh
    sshpass
    curl
    python3
    coreutils
    gnused
    gawk
  ];

  scripts = {
    detect-origin = app "detect-origin" {runtimeInputs = with pkgs; [iproute2 gawk];};
    net-setup = app "net-setup" {runtimeInputs = with pkgs; [iproute2 nftables iptables];};
    host-install = app "host-install" {
      runtimeInputs = with pkgs; [coreutils systemd];
      text = substituted "host-install";
    };
    microvm = app "microvm" {
      runtimeInputs = [pkgs.nix pkgs.iproute2 scripts.detect-origin];
    };
    users = app "users" {runtimeInputs = propagationInputs;};
    seed = app "seed" {
      runtimeInputs = propagationInputs ++ [scripts.detect-origin];
    };
    provision = app "provision" {runtimeInputs = propagationInputs;};
    clients = app "clients" {
      runtimeInputs = propagationInputs ++ [pkgs.nix scripts.provision];
    };
  };
in
  scripts
